// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartShelf.web.Data;

#nullable disable

namespace SmartShelf.web.Migrations
{
    [DbContext(typeof(SmartShelfContext))]
    [Migration("20260411190135_AddMissedScanCount")]
    partial class AddMissedScanCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartShelf.web.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Threshold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("SmartShelf.web.Models.Reader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reader");
                });

            modelBuilder.Entity("SmartShelf.web.Models.Tag", b =>
                {
                    b.Property<string>("EPC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("EPC");

                    b.HasIndex("ProductId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("SmartShelf.web.Models.TagCurrentState", b =>
                {
                    b.Property<string>("EPC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Antenna")
                        .HasColumnType("int");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastSeenTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("MissedScanCount")
                        .HasColumnType("int");

                    b.Property<int>("ReadCount")
                        .HasColumnType("int");

                    b.Property<int>("ReaderId")
                        .HasColumnType("int");

                    b.Property<int>("Rssi")
                        .HasColumnType("int");

                    b.HasKey("EPC");

                    b.HasIndex("ReaderId");

                    b.ToTable("TagCurrentState");
                });

            modelBuilder.Entity("SmartShelf.web.Models.TagReadEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Antenna")
                        .HasColumnType("int");

                    b.Property<string>("EPC")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<int>("ReadCount")
                        .HasColumnType("int");

                    b.Property<int>("ReaderId")
                        .HasColumnType("int");

                    b.Property<int>("Rssi")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EPC");

                    b.HasIndex("ReaderId");

                    b.ToTable("TagReadEvent");
                });

            modelBuilder.Entity("SmartShelf.web.Models.Tag", b =>
                {
                    b.HasOne("SmartShelf.web.Models.Product", "Product")
                        .WithMany("Tags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartShelf.web.Models.TagCurrentState", b =>
                {
                    b.HasOne("SmartShelf.web.Models.Tag", "Tag")
                        .WithOne("CurrentState")
                        .HasForeignKey("SmartShelf.web.Models.TagCurrentState", "EPC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartShelf.web.Models.Reader", "Reader")
                        .WithMany("TagCurrentStates")
                        .HasForeignKey("ReaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reader");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SmartShelf.web.Models.TagReadEvent", b =>
                {
                    b.HasOne("SmartShelf.web.Models.Tag", "Tag")
                        .WithMany("TagReadEvents")
                        .HasForeignKey("EPC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartShelf.web.Models.Reader", "Reader")
                        .WithMany("TagReadEvents")
                        .HasForeignKey("ReaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reader");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SmartShelf.web.Models.Product", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("SmartShelf.web.Models.Reader", b =>
                {
                    b.Navigation("TagCurrentStates");

                    b.Navigation("TagReadEvents");
                });

            modelBuilder.Entity("SmartShelf.web.Models.Tag", b =>
                {
                    b.Navigation("CurrentState");

                    b.Navigation("TagReadEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
